/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CompanyAdmin: typeof import('./src/components/CompanyAdmin.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SuperAdmin: typeof import('./src/components/SuperAdmin.vue')['default']
    TelekomAdmin: typeof import('./src/components/TelekomAdmin.vue')['default']
  }
}
